Enable code signing.

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -22,6 +22,8 @@ env:
   INNOSETUP_VERSION: 6.7.1
   VALENTINA_VERSION: 1_0_0
   ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
+  # Set the URL as an environment variable for the cache key
+  SIMPLYSIGN_URL: 'https://files.certum.eu/software/SimplySignDesktop/Windows/9.4.2.86/SimplySignDesktop-9.4.2.86-64-bit-en.msi'
 
 jobs:
   build:
@@ -36,9 +38,11 @@ jobs:
             label: Qt6_8
             run_tests: 'true'
             deploy: 'true'
+            sign: true
 
     env:
       DEPLOY: ${{ matrix.qt.deploy }}
+      SIGN: ${{ matrix.qt.sign }}
       RUN_TESTS: ${{ matrix.qt.run_tests }}
       WITH_CRASH_REPORTING: 'True'
       INSTALL_QT: ${{ matrix.qt.install }}
@@ -165,6 +169,35 @@ jobs:
         shell: bash
         run: conan install . --build=missing -o '&:with_crash_reporting=${{ env.WITH_CRASH_REPORTING }}' -o '&:with_xerces=True' -pr:a=share/ci/conan/profiles/windows
 
+      - name: Cache SimplySign Installer
+        uses: actions/cache@v5
+        with:
+          # This is the path where the installer will be saved by the action
+          path: SimplySignDesktop.msi
+          # The key ensures we get a new download if the URL changes
+          key: simplysign-msi-${{ env.SIMPLYSIGN_URL }}
+
+      - name: Setup Certum SimplySign environment
+        uses: dismine/windows-app-signing-setup-action@v1
+        with:
+          certum-username: ${{ secrets.CERTUM_USERNAME }}
+          certum-otp-uri: ${{ secrets.CERTUM_OTP_URI }}
+          certum-key-id: ${{ secrets.CERTUM_KEY_ID }}
+
+      - name: Add SignTool to PATH
+        shell: pwsh
+        run: |
+          $signtool = Get-ChildItem -Path "C:\Program Files (x86)\Windows Kits\10\bin\" -Filter signtool.exe -Recurse | Where-Object { $_.FullName -match 'x64' } | Select-Object -First 1
+          
+          if ($signtool) {
+              $signtoolDir = Split-Path $signtool.FullName
+              Write-Host "✅ Adding SignTool to PATH: $signtoolDir"
+              echo "$signtoolDir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
+          } else {
+              Write-Error "❌ SignTool.exe not found in Windows SDK folders."
+              exit 1
+          }
+
       - name: Set up common Qbs args
         shell: bash
         run: >
@@ -174,6 +207,8 @@ jobs:
           config:release
           qbs.installRoot:\"$RUNNER_TEMP/build/release/install-root/valentina\"
           profile:qt6
+          project.enableSigning:${{ env.SIGN }}
+          modules.buildconfig.signingThumbprint:${{ secrets.CERTUM_KEY_ID }}
           project.enableConan:true
           project.conanWithCrashReporting:${{ env.WITH_CRASH_REPORTING }}
           project.conanWithXerces:true
@@ -220,6 +255,16 @@ jobs:
         shell: bash
         run: qbs -p autotest-runner ${{ env.COMMON_QBS_ARGS }}
 
+      - name: Sign binaries
+        if: github.event_name != 'pull_request' && env.DEPLOY == 'true'
+        shell: pwsh
+        env:
+          CERTUM_KEY_ID: ${{ secrets.CERTUM_KEY_ID }}
+        run: |
+          & "./scripts/sign-binaries.ps1" `
+            -InstallRoot "$env:RUNNER_TEMP\build\release\install-root\valentina" `
+            -CertumKeyId $env:CERTUM_KEY_ID  
+
       - name: Create installer
         if: github.event_name != 'pull_request' && env.DEPLOY == 'true'
         shell: bash
@@ -257,9 +302,11 @@ jobs:
             tools: 'tools_mingw81,qt.tools.win32_mingw810'
             build_arch: 'x86'
             deploy: 'true'
+            sign: true
 
     env:
       DEPLOY: ${{ matrix.qt.deploy }}
+      SIGN: ${{ matrix.qt.sign }}
       RUN_TESTS: 'true'
       QT_VERSION: ${{ matrix.qt.label }}
       COMPILER: ${{ matrix.qt.compiler }}
@@ -323,6 +370,35 @@ jobs:
           qbs-config.exe profiles.qt5.baseProfile ${{ env.COMPILER }}
           qbs-config --list profiles
 
+      - name: Cache SimplySign Installer
+        uses: actions/cache@v5
+        with:
+          # This is the path where the installer will be saved by the action
+          path: SimplySignDesktop.msi
+          # The key ensures we get a new download if the URL changes
+          key: simplysign-msi-${{ env.SIMPLYSIGN_URL }}
+
+      - name: Setup Certum SimplySign environment
+        uses: dismine/windows-app-signing-setup-action@v1
+        with:
+          certum-username: ${{ secrets.CERTUM_USERNAME }}
+          certum-otp-uri: ${{ secrets.CERTUM_OTP_URI }}
+          certum-key-id: ${{ secrets.CERTUM_KEY_ID }}
+
+      - name: Add SignTool to PATH
+        shell: pwsh
+        run: |
+          $signtool = Get-ChildItem -Path "C:\Program Files (x86)\Windows Kits\10\bin\" -Filter signtool.exe -Recurse | Where-Object { $_.FullName -match 'x64' } | Select-Object -First 1
+          
+          if ($signtool) {
+              $signtoolDir = Split-Path $signtool.FullName
+              Write-Host "✅ Adding SignTool to PATH: $signtoolDir"
+              echo "$signtoolDir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
+          } else {
+              Write-Error "❌ SignTool.exe not found in Windows SDK folders."
+              exit 1
+          }
+
       - name: Set up common Qbs args
         shell: bash
         run: >
@@ -332,6 +408,8 @@ jobs:
           config:release
           qbs.installRoot:\"$RUNNER_TEMP/build/release/install-root/valentina\"
           profile:qt5
+          project.enableSigning:${{ env.SIGN }}
+          modules.buildconfig.signingThumbprint:${{ secrets.CERTUM_KEY_ID }}
           modules.buildconfig.enablePCH:true
           modules.windeployqt.compilerRuntime:true
           modules.windeployqt.noCompilerRuntime:false" >> $GITHUB_ENV
@@ -344,6 +422,16 @@ jobs:
         if: env.RUN_TESTS == 'true'
         shell: bash
         run: qbs -p autotest-runner ${{ env.COMMON_QBS_ARGS }}
+
+      - name: Sign binaries
+        if: github.event_name != 'pull_request' && env.DEPLOY == 'true'
+        shell: pwsh
+        env:
+          CERTUM_KEY_ID: ${{ secrets.CERTUM_KEY_ID }}
+        run: |
+          & "./scripts/sign-binaries.ps1" `
+            -InstallRoot "$env:RUNNER_TEMP\build\release\install-root\valentina" `
+            -CertumKeyId $env:CERTUM_KEY_ID
 
       - name: Create installer
         if: github.event_name != 'pull_request' && env.DEPLOY == 'true'
